name: Pull today's scores

on:
  workflow_dispatch:
  schedule:
    - cron: '6 6 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Scrape EPSS scores for current date
      run: |-
        # Set time zone to EST
        export TZ=America/New_York
        
        # Save current date as YYYY-MM-DD format
        date=$(date +%Y-%m-%d)

        # Construct URL with current date
        url="https://epss.cyentia.com/epss_scores-${date}.csv.gz"

        # Log URL being called
        echo "Downloading from URL: ${url}"

        # Download and uncompress CSV file from URL, save to file
        curl -s "${url}" | gzip -d -c > | tail -n +2 > epss.csv

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update data: ${timestamp}" || exit 0
        git push
